name: thinking_analytics
description: Official flutter plugin for tracking events to Thinking Analytics.
version: 1.0.0
homepage: https://www.thinkingdata.cn
repository: https://github.com/ThinkingDataAnalytics/flutter-sdk

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: cn.thinkingdata.flutter
    pluginClass: ThinkingAnalyticsPlugin

